[package]
name = "metamast"
version = "0.1.0"
authors = ["Antoine Choppin <antoine@japonophile.com>"]
edition = "2018"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
mockall = "0.6.0"
regex = "0.2"
lazy_static = "1.4.0"

